-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Feb 26, 2017 at 11:08 AM
-- Server version: 10.1.19-MariaDB
-- PHP Version: 5.6.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `synapse`
--

-- --------------------------------------------------------

--
-- Table structure for table `login`
--

CREATE TABLE `login` (
  `id` int(11) NOT NULL,
  `name1` varchar(20) NOT NULL,
  `name2` varchar(20) NOT NULL,
  `email` varchar(30) NOT NULL,
  `team_name` varchar(30) NOT NULL,
  `mobile` double NOT NULL,
  `college` varchar(30) NOT NULL,
  `password` varchar(15) NOT NULL,
  `q1` varchar(50) NOT NULL,
  `q2` varchar(50) NOT NULL,
  `q3` varchar(50) NOT NULL,
  `q4` varchar(50) NOT NULL,
  `q5` varchar(50) NOT NULL,
  `q6` varchar(50) NOT NULL,
  `q7` varchar(50) NOT NULL,
  `q8` varchar(50) NOT NULL,
  `q9` varchar(50) NOT NULL,
  `q10` varchar(50) NOT NULL,
  `q11` varchar(50) NOT NULL,
  `q12` varchar(50) NOT NULL,
  `q13` varchar(50) NOT NULL,
  `q14` varchar(50) NOT NULL,
  `q15` varchar(50) NOT NULL,
  `q16` varchar(50) NOT NULL,
  `q17` varchar(50) NOT NULL,
  `q18` varchar(50) NOT NULL,
  `q19` varchar(50) NOT NULL,
  `q20` varchar(50) NOT NULL,
  `lastq` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `login`
--

INSERT INTO `login` (`id`, `name1`, `name2`, `email`, `team_name`, `mobile`, `college`, `password`, `q1`, `q2`, `q3`, `q4`, `q5`, `q6`, `q7`, `q8`, `q9`, `q10`, `q11`, `q12`, `q13`, `q14`, `q15`, `q16`, `q17`, `q18`, `q19`, `q20`, `lastq`) VALUES
(33, 'guru', 'hardik', 'rad@gmail.com', 'randi', 9696969696, 'daiict', '123456', 'asdhjdfadafo', 'NULL', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(34, 'Yash Mirani', 'Prateek Celly', 'miraniy98@gmail.com', 'Brainstormers', 9725500271, 'DA-IICT', 'teamjitegi', 'Nobel Prize Exhibition inauguration(Vibrant Gujara', 'tokyo(japan)', 'sushant divgikar', 'donald trump', 'platinum', 'the good the bad and the ugly', '14 february(valentines day)', 'If you can''t feed a hundred people, then feed just', 'june', 'nucleya', 'thomas alva edison', 'murali vijay', 'Beauty and the beast', '2012', 'NULL', 'NULL', 'speed', 'dead sea', 'PSLV-C37', 'Allan jones', 1),
(35, 'Manan kshatriya', 'Shashwat mishra', '201401228@daiict.ac.in', 'Ganymede', 9825619435, 'Daiict', 'm1a2n3a4n5', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(36, 'Hilloni Shah', 'Khanti Rindani', 'hilloni98@gmail.com', 'Dreamers', 8469546470, 'daiict', 'dreamers', 'Nobel prize shared by two', 'Rio de Janeiro', 'gay company', 'west indies', 'C. Rajagopalachari', 'clint eastwood outlaw josey wales', '14 February 2017', 'All work and no play makes Jack a dull boy', 'june', 'tnt band', 'thomas edison', 'butler', 'fiction', '2011', 'mario', 'the dirty picture', '', '', '', '', 0),
(37, 'Parita Sheth', 'Mansi Od', 'shethparita98@gmail.com', 'Lock and key', 9687156617, 'Daiict', 'lockandkey', 'NULL', 'Tokyo', 'NULL', 'Usain Bolt', 'Bharat Ratna', 'The outlaw Josey wales', '14-2-2017', 'NULL', '21st June', 'Blood,Sweat,Tears', 'NULL', 'Sachin Tendulakar', '', '', '', '', '', '', '', '', 0),
(38, 'Urvashi Banthia', 'Devla', 'urvashijain66@gmail.com', 'Set', 8000241589, 'DA-IICT', '1234567890', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(39, 'Mansi Ambalam', 'Palak Kanzariya', 'maverick230898@gmail.com', 'Phalange', 8469762396, 'V.V.P. Engineering College', 'raina48036557', 'Al jazeera', 'Tokyo', 'Tim cook', 'Serena Williams', 'M. Visvesvaraya', 'Outlaw Josey Wales', '14 February, 2017', 'NULL', 'June', 'Realized fantasies', 'Haneefa', 'Don bradman', '', '', '', '', '', '', '', '', 0),
(40, 'Jaydeep Eraniya', 'Vishva Patel', 'jaydeeperaniya17jd@gmail.com', 'Eratel', 7567778710, 'DA-IICT', 'abcd1234', 'Nobel Prize shared between two people.', 'Pyeongchang	South Korea	2018 Next olympic Country', 'Sundar Pichai Google ceo', 'Sportsperson Related Wrestling.', 'NULL', 'The Outlaw Josey Wales', '14-Feb Valentines Day', 'NULL', 'June', 'The Local Train band.', 'M. B. Haneefa', 'NULL', 'love is life', '2011', 'Piano ', 'The Dirty Picture', 'Sonic Dash Angry Birds', 'NULL', 'Pokemon Go', 'Cyril Hume', 1),
(41, 'Ashwin Porwal ', 'Ankit kamal', 'ashwinporwal8@gmail.com', 'Chip and dale', 7486801397, 'DAIICT', 'Ash23111996', 'NULL', 'taj mahal', 'Benhur Samson', 'Waqar Hasan', 'Sir Mokshagundam Visvesvaraya ', 'the wild wild west', '14 February 1990', 'Beggars canâ€™t be choosers', 'june', 'metallica', 'thomas edison', 'Roger Federer', 'beauty and the beast', '2016', 'juggler', 'the dirty picture', 'sonic dash', '', '', '', 0),
(42, 'Vishnu Kanduri Sreen', 'Samarth Saxena ', 'slvkbonded@gmail.com', 'Orion', 7487051156, 'DAIICT', 'Slvkbonded@+1', 'Yoshinori Ohsumi', 'Eiffel Tower', 'Ted Cruz', 'Powerball $217 million', 'Bharat Ratna', 'The good, the Bad and The Ugly', 'February 14th', 'Necessity, not Scarcity, is the mother of inventio', 'Juine', 'METALLICA', 'Thomas Alva Edison', 'Ravindra Jadeja', 'Ranger', '2011', 'Guinness World Records', 'NULL', 'genes', 'NULL', 'App tops the google play store', '', 0),
(43, 'Ayushi Malhotra', 'Nishi Doshi', 'ayushimalhotra9799@gmail.com', 'The Ultimate Deciphers', 9978319456, 'DAIICT', 'ayuni916', 'demonetization', 'tokyo', 'united states', 'wimbledon', 'bharat ratna', 'NULL', 'bangalore', 'NULL', 'june', 'explosives', 'light detection device', 'victory', 'movies', 'osama bin laden''s sudanese wife', 'Mario', 'NULL', 'NULL', 'NULL', 'NULL', '', 0),
(44, 'Sahil Dadhoriya', 'Rutvij Patel', 'immsd.001@gmail.com', 'Banti Samaj', 8160623323, 'Daiict', '45646444', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(45, 'Parth Doshi', 'Dharmil Gandhi', 'parthdoshi2468@gmail.com', 'Limited_Edition', 7575041790, 'DA-IICT', 'parth@c318', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(46, 'Harsh Doshi', 'Prashil Shah', 'Doshiharsh29@gmail.com', 'Paheli Hackers', 9033159831, 'GLS institute of business admi', 'glsharsh@123', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(47, 'Sneha', 'Twisha', 'mandansneha@gmail.com', 'Swish', 8128476467, 'DA-IICT', 'swish96', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(48, 'ADARSH MISRA', 'KISHAN KUMAR PATEL', 'pkishan2207@gmail.com', 'Gotcha!!', 9537524200, 'DAIICT', 'Password', 'Noble Peace Prize ', 'TOKYO', 'Tim Cook', 'Steelers wins in Rugby', 'God of the game', 'The good, The Bad, The Ugly', 'Crush', 'No Greater Love by Thomas Moore', 'INTERNATIONAL YOGA DAY 21st JUNE @)!%', 'Disasters', 'kaabil', 'Ravindra Jadeja', 'Audi', '1898', 'Mario', 'NO one killed jessica', 'adrenaline rush', 'Sea cost', 'Team rocket beats Ash', 'Cyril Hume', 1),
(49, 'Vedant', 'Hitesh', 'gvedant40@gmail.com', 'VgHp', 9426478484, 'Da-iict', '08021994', 'C.V RAMAN', 'TOKYO', 'TIM COOK', 'John Isner', 'Sir Mokshagundam Visvesvaraya', 'The Good, the Bad and the Ugly', 'Feb 14', 'An idle mind is the Devil''s workshop ', 'June', 'TELL NO TALES(TNT)', 'swades', 'virender sehwag', 'Dino charger', '2011', 'The Legend of Zelda', 'ramayan', 'NULL', 'NULL', 'NULL', 'williams shakespeare', 1),
(50, 'Mit Naria', 'Suparshva Mehta', 'mitnaria@gmail.com', 'Roomies', 9924476971, 'DAIICT', '301devbhumi', 'Linus Pauling', 'tokyo', 'tim cook', 'john isner', 'true blue', 'the good bad and ugly', 'valentine''s day', 'The chief thing for life is water, and bread, and ', 'june', 'tnt', 'swades', 'Mohit Ahlawat', 'mercedes', '2011', 'mario', 'ramleela', 'gene', '', '', '', 0),
(52, 'Mihir Thakkar ', 'Jitesh Sanghvi', 'mihirthakkar2017@gmail.com', 'Targaryens', 9586154368, 'DA-IICT', 'sherlocked', 'Swami Vivekananda', 'Tokyo', 'Tim Cook', 'NULL', 'Mokshagundam Visvesvaraya,', 'the Good, the Bad, and the Ugly ', 'February 15', 'necessity is the mother of invention', 'June', 'Benzene', 'Thomas Alva Edison', 'Ravindra Jadeja', 'Jaguar XJ', '2011', 'Super Mario', 'The Dirty Picture', 'DNA', 'NULL', '104 satellites by ISRO', '', 0),
(53, 'Rajat Garg', 'Mihir Shah', 'gtech1996@gmail.com', 'BEERUS WHIS', 7405817793, 'Dhirubhai Ambani Institute of ', '123456789', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 1),
(54, 'Dilip Kumar Meena', 'Pooja Tiwari', 'd49web@gmail.com', 'Spectre', 9737984409, 'DA-IICT', '1996Dipu', 'nobel prize', 'Pyeongchang', 'Tim Cook', 'Roger Federer', 'India', 'The Good, the Bad and the Ugly', '14th feb', 'Adversity is the mother of wisdom', 'june', 'Demon Hunter', 'thomas edison', 'Paul Hunter', 'Audi', '2011', 'NULL', 'kahaani', 'runner', 'bermuda triangle', 'NULL', '', 0),
(55, 'Abhi Zanzarukiya', 'Vishrut Jetly', 'zanzarukiaabhi@gmail.com', 'Savage-2', 8758719777, 'Dhirubhai Ambani Institute of ', 'synapseabhi', 'vounch', 'tokyo (japan)', 'Tim cook', 'Pete Samparas(Wimbledon Cup Winner)', 'M.Visvesvaraya', 'clint eastwood the good the bad and the ugly ', '14th feb(Valentine''s Day)', 'Neccessity is the mother of invention', 'june', 'Hell BAnd', 'Thomas Alva Edison', 'NULL', 'bike', '2011', 'mario', 'ram teri ganga meli', 'chromosome', 'theb gamer', 'isro', 'william shakespeare', 1),
(56, 'Rajat Shah', 'Neel Parmar', 'rajatshah622@gmail.com', 'Crobats', 8154825877, 'DAIICT', 'qwerty010', 'Shapes', 'Tokyo', 'tim cook', 'NULL', 'Sir', 'Wild West', 'NULL', 'NULL', 'NULL', '', '', '', '', '', '', '', '', '', '', '', 0),
(57, 'Sudipta Haldar', 'Tanay Borkar', 'tangreat.bk@gmail.com', 'Pagle', 9512079706, 'DA-IICT', 'dilbur', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(58, 'SMIT DETROJA', 'GAURANG BADIYANI', 'smitdetroja96.sd@gmail.com', 'THE DECIPHERS', 9428862968, 'DA-IICT', 'SmitGaurang', 'Demonetisation', 'Pyeongchang County,South Korea', 'Tim Cook', 'NASCAR SPRINT CUP MARTINSVILLE SPEEDWAY', 'Sir Sachin Tendulkar', 'The Good,The Bad and The Ugly', '14 February', 'NULL', 'June', 'Texas TNT', 'Thomas Edison', 'Ronnie o''sullivan ', 'Aston Martin', '2011', 'NULL', 'NULL', 'NULL', 'Australia', 'NULL', 'NULL', 1),
(59, 'Pratik Wankhede', 'Aayush Agarwal', '201501129@daiict.ac.in', 'Obviously Not Sherlocks', 7405108431, 'DA-IICT', 'Plasma@007078', 'Vibrant Gujarat', 'Tokyo (2020 Olympics)', 'Same sex marriage bureau', 'NULL', 'Sir Sachin Tendulkar', 'The Outlaw Josey Wales', 'Bangalore', 'Mother Teresa', 'International yoga Day', 'Oklahama City thunder', 'Shyam Saran Negi', 'Spartans', '2017 movies', 'NULL', 'Nintendo', 'Ram teri ganga maili', 'Superman', 'Miami', '', '', 0),
(60, 'Yash shah ', 'Dhruv Jadav ', 'yashdevyami@gmail.com', ' highfuntioning sociopaths  ', 9925069749, 'DAIICT', '@7Janamdmy', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(62, 'Riddhi Thakker', 'Anushka Desai', 'riddhithakker26@gmail.com', 'Fearless Searchers', 8320637958, 'DA-IICT', 'Mycroft_Holmes', 'black money', 'tokyo', 'Satya Nadella', 'wimbledon', 'commonwealth', 'the good, the bad and the ugly', 'Royal Challengers bangalore', 'canonisation', 'International Yoga day, 21 June', 'AC/DC', 'thomas edison', 'kolkatta', 'NULL', '2011', 'super mario bros', 'NULL', 'shh', '', '', '', 0),
(63, 'Hardik Modi', 'Nikesh B Parekh', 'nikesh04parekh@gmail.com', 'Wide Vision', 7383872518, 'DAIICT', 'NH@widevision', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(64, 'Dhruvil Patel', 'Hardik Patel', 'hardik3413@gmail.com', 'Team Expendebles', 8153099537, 'DA-IICT', 'patidarking', 'Nobel prize is unshareble', 'Pyeongchang in South  Korea', 'Tim Cooke, Apple CEO ', 'in cricket worldcup out of 12 team one team win wo', ' Kidnap Sachin Tendulkar to bolster visitorsâ€™ ba', 'NULL', '14th february,2017', 'NULL', 'june', 'the local train', 'Haneefa', 'sachin tendulkar made 300 8 times', 'NULL', 'in 2011', 'NULL', 'dirty picture', 'flash', '', '', '', 0),
(65, 'Keval Dave', 'Mansi Singh', 'keval.dave1@gmail.com', 'Load', 8511161385, 'DA-IICT', '1994keval', 'Inaugurated the Nobel Prize exhibition', 'Japan', 'Tim cook', 'NULL', 'British Prime Minister Gordon Brown''s  honoured Sa', 'THE GOOD THE BAD & THE UGLY', '14 February', 'Necessity is the mother of invention ', 'June', 'Thunderstorm', 'Thomas Edison', 'Sachin Tendulkar', 'Range Rover beasley', '2011', 'NULL', '', '', '', '', '', 0),
(66, 'Mayank kumar Jethwa', 'Hardiki Devre', 'mayankjansari28@gmail.com', 'Sayonara', 7433064276, 'DA-IICT', 'swami@2403', 'Narendra Modi maiden speech at UN assembly', 'next olympics held at tokyo', 'Tim Cook is the only openly gay CEO of a Fortune 5', 'JImmy Walker with his PGA Championship victory', 'NULL', 'the outlaw josey wales', '14 february', 'Early to bed and early to rise, makes a man health', 'june month fit yoga day', 'Tianjin explosion', 'NULL', '', '', '', '', '', '', '', '', '', 0),
(67, 'Rishita ', 'Shefali ', 'kashyap.shefali95@gmail.com', 'Kudos ', 7300136112, 'Daiict ', '12345678', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(68, 'Jay Dave', 'Mitraiya Patel', '201601224@daiict.ac.in', 'sher-son', 7043300725, 'DAIICT', 'Qwerty@1234', 'unshared nobel price to modi', 'peru', 'tim cook', 'piano', 'dhyan chand', 'starring inthe good ,the bad and the ugly...(dolla', 'valentine day ', 'campfire', 'yoga day at 21 june (lunius or  little eintiens ju', 'death or coma', 'media preservation survey', '', '', '', '', '', '', '', '', '', 0),
(69, 'Sagar Nasit', 'Ninad Mehta', 'ninadmehta1996@gmail.com', '2', 8460043338, 'Dhirubhai Ambani Institute of ', '9408964383', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(70, 'SMIT PATEL', 'MIT SWAMI', 'patelsmit32123@gmail.com', 'DA_pneumonoultramicroscopicsil', 9512679129, 'DAIICT', 'zxcvbnm,./', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(72, 'Pankil Panchal', 'Jeet Patel', '201601141@daiict.ac.in', 'The ChainSmokers', 8469253626, 'DA-IICT', 'iamP.cube9999', 'Harold Varmus', 'japan', 'Tim Cook', 'south korea YG Entertainment', 'bharat ratna in sports', 'the good,the bad,the ugly', '14 february', 'A child miseducated is a child lost', '21 June', 'The Chemical Brothers', 'thomas edison', 'Virender Sehwag', 'the power of now', '2011', 'super mario', 'ramayana', 'jumping genes', 'red sea', 'sundance film festival', 'willian shakespere', 1),
(73, 'Meet Shah', 'Dhaval Prajapati', 'meetshah7202@gmail.com', 'D-202 Holmes', 9033477202, 'DA-IICT', 'holmes', 'modi wins nobel prize for mitron particle.', 'tokyo,japan', 'Tim Cook', 'Sushila Chanu', 'president''s day', 'The Good, The Bad, and The Ugly', '15 feb 2017', 'Mold childen''s mind as you train', 'june', 'Glow Stick', 'addison evm', 'Virender Sehwag ', 'rangrover', '2011', 'God of War', 'the dirty picture', 'gamming', 'share lock homes', '37 attecks ', 'vishal', 1),
(74, 'Nikisha', 'Soumya', 'nikisha12345@gmail.com', 'SexiNexi', 9978212666, 'DAIICT', 'niki1997', 'Nobel Prize Series India', 'Tokyo, Japan', 'Fortune 500 Homosexuality Non discrimination Proje', 'Wimbledon''s longest match lasted 11hour 5mins', 'Sachin T. to receive knighthood in 2008', 'The good, the bad, the ugly-1966', 'All occurred on feb14,- youtube-2005,anushka in 20', 'Mumbai Designer''s logo chosen for mother teresa''s ', 'International Yoga day - 21 June', 'ac/dc songs :- thunderstruck ,highway to hell,tnt', 'swades', 'Number 8 common ', 'All owned by disney-sleeping  beauty, beauty and t', 'All occurred in 2011: marriage 29April,killing of ', 'Pokemon Go owned by Nintendo breaks many world rec', 'Kahaani', '', '', '', '', 0),
(75, 'Kushal Parikh', 'Priyank Sevak', 'kushal.1376@gmail.com', 'google', 9586018601, 'DAIICT', 'kingkiller1376', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(76, 'Cvvb', 'Ghg', 'Fffd@dds.com', 'Ffghu', 7656546543, 'Da', '123456', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(77, 'kashyap', 'Ankit', 'kashyapgohil476@gmail.com', 'Brothers', 9727216771, 'DAIICT', 'Brothers', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(78, 'Pragnesh', 'Rushi', 'pragneshnonghanvadra@gmail.com', 'Royal$', 9978423362, 'DAIICT', 'Royal$', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(79, 'Kuntal Nayak', 'Parth Rajdev', '201401223@daiict.ac.in', 'stainedAsh', 9714714154, 'DA-IICT', 'stainedAsh', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(80, 'Kenneth Tenny', 'Parul Bindal', 'parulbindal96@gmail.com', 'TeamLife', 7567806095, 'IIIT Vadodara', 'parul$$321', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(81, 'Ritika Ritu', 'Sabiha Tanzeer', 'rtkrt5@gmail.com', '221B', 8264598874, 'NIFT GANDHINAGAR', 'rsr123', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(82, 'Brij Desai', 'Siddharthsinh Rana', '201401119@daiict.ac.in', 'true detectives', 9512022027, 'DAIICT', '12345678', 'NULL', 'Tokyo', 'Tim Cook', 'Brian Lara', 'Mokshagundam Visvesvaraya', 'The Good, the Bad and the Ugly', '14 February ', 'I was hungry, and you gave me something to eat, I ', 'June', 'TNT', 'Thomas Alva Edison', 'Ravindra Jadeja', 'The Beast', '2011', 'Mario', 'The Dirty Picture', '', '', '', '', 0),
(83, 'Dangar', 'PK', 'eagle11061997@gmail.com', 'Noobs', 8160047030, 'same', 'md1161997', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(84, 'Krishanu Konar', '-', '201401127@daiict.ac.in', 'SullySeagate', 9737032174, 'DA-IICT', '123456789', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(85, 'Srk', 'Bhai', 'Raees@bhaijan.com', 'Raees', 7867867867, 'Daru ka business', 'srkrocks', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(86, 'Karn vadaliya', 'Priyam suthar', 'karn.vadaliya@gmail.com', 'Anonymous', 8980433856, 'DAIICT', 'karn_priyam', 'ronald ross', 'taj mahal', 'Tim cook', 'roger federer', 'M. Visvesvaraya', 'the good,the bad and ugly', 'valentines day', 'howard head', 'june', 'explosive TNT', '', '', '', '', '', '', '', '', '', '', 0),
(87, 'KRITI', 'RAVALI', 'kritichandra21@gmail.com', 'Hackslash', 7486895249, 'DAIICT', 'Kriti@21021992', 'why PM Modi deserves a nobel prize', 'NULL', 'fortune 500', 'Josep Maria Bartomeu Floreta', 'rajyavardhan singh rathore', 'The Outlaw Josey Wales', '14th feb 1990', 'Necessity is the mother of invention', 'June', 'tnt', 'Thomas edison', 'NULL', 'NULL', '2011', 'NULL', 'NULL', 'NULL', 'NULL', 'pokemon go', '', 0),
(88, 'NIKITA LODHA', 'NIKITA VISHWAKARMA', 'nickylodha09@gmail.com', 'N-Square', 7048386784, 'DAIICT', 'nikita0918', 'Demonetisation', 'NULL', 'Tim Cook', 'YG Winner', 'metal', 'cowboys', 'rumour', 'roti, kapda aur makaan', 'International yoga day', 'explosion', 'Swadesh', 'victory day', 'Beauty and beast', 'SPAIN', 'ATLANTA', 'PAHELI', 'SEGA', 'Philippines', 'Regner Grasten', 'WILLIAM SHAKESPEARE', 1),
(89, 'Chirag', 'Jayesh Udhani', 'chiragc204@gmail.com', 'helloworld!', 9033631675, 'DA-IICT', '123456', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(90, 'Megh Choksi', 'Manohar Sinh Rana', '201601093@daiict.ac.in', 'whiteopink', 9824106441, 'DA-IICT', '17291729', 'narendra modi inagurated nobel prize series exibit', 'TOKYO,JAPAN', 'benhur samson surrogacy abroad ', 'south korea winter olympics 2018', 'NULL', 'The Good, the Bad and the Ugly', '14 February valentine''s day', 'girl house t shirt glass house', 'june', '"thunderstrock" song created by tnt band', 'thomas edison', 'sportsman of greece t shirt no 8 brand addidas', 'jet jammer', '2011', 'nintendo', 'NULL', 'NULL', 'NULL', 'NULL', '', 0),
(91, 'Ashish', 'Bharat', 'ashishvaishnav481929@gmail.com', 'RedHat', 9726915303, 'DAIICT', 'ashish10!', 'Linus Pauling', 'Tokyo', 'Tim Cook', 'Holger Waldenberger', '15th September', 'The Good, the Bad and the Ugly', '14th February', 'The fame has completely gone to my head.', 'June', 'TNT', 'Thomas A. Edison', 'Virender Sehwag', 'Range Rover', '2011', 'PlayStation', 'Hamaari Adhoori Kahaani', '', '', '', '', 0),
(92, 'Kirtan patel', 'Tanik Pansuriya', '201601081@daiict.ac.in', 'googlock Watson', 9825266550, 'DAIICT', '123456789', 'Vibrant gujarat', 'Eiffel tower', 'tim cook, apple ceo', 'NULL', 'tribhawan kaul', 'NULL', 'harrison fords plane nearly crashed', 'NULL', 'june', 'destruction', '', '', '', '', '', '', '', '', '', '', 0),
(93, 'Piyush Ajmeria', 'Rishabh Arora', 'piyushajmeria1@gmail.com', 'DidYouMissMe', 7600425359, 'DA-IICT', 'piyushrishabh', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(94, 'Roshan Shah', 'Purohit Devansh', 'dnpurohit96@gmail.com', 'RemoKeRangeele', 9586575161, 'DAIICT', 'didlittlechamps', 'Kailash Satyarthi', 'Tokyo', 'Tim Cook', 'Usain Bolt', 'Sri. M. Visvesvaraya', 'The Good, the Bad and the Ugly', 'Valentines day', 'necessity is the mother of invention', 'world yoga day 21 june', 'TNT', 'Electronic Voting Machine', 'azhar ali', 'Mercedes-Benz SLK 55 AMG', '2011', 'monopoly', 'Dirty Picture', 'Sonic hedgehog', 'bermuda triangle', 'rocket selfie', 'william Shakespeare', 1),
(95, 'Samhitha Gundam', 'Sakshee  Patel', 'samhitha.gundam@gmail.com', 'Gryffindor ', 7486914506, 'DAIICT', 'sakshee', 'Demonatisation', 'Tokyo', 'Tim Cook', 'John Isner', 'NULL', 'The Good,Bad and ugly', 'february 14', 'NULL', 'June', 'nitro', 'AlbertEinstein', 'Subhash Agarwal', 'NULL', '1993', 'NULL', '', '', '', '', '', 0),
(96, 'Mausam Mehta', 'Vanshika Darbari', 'vanshikadarbari@yahoo.com', 'Unbowed unbent unbroken', 9974893812, 'DAIICT', 'portmanteau123', 'Peace', 'Tokyo', 'Global fortune 500', 'Times''  winner', 'Controversy on sachin tendulkar''s knighthood', 'The Outlaw Josey Wales', '14 february', 'Money is the root of all evill', 'June', 'AC/DC', 'Thomas Alva Edison', 'Virat Kohli', 'Ferrari', '2011', 'NULL', '', '', '', '', '', 0),
(97, 'Kaushal Patel', 'Darsh Vajaria', 'kau353655@gmail.com', 'Brachistochrone', 8511571065, 'DA-IICT', '12345678', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(98, 'Hirva Patel', 'Parshva Shah', 'hirvap08@gmail.com', 'Meilleurs', 9409668841, 'G H Patel College Of Engineeri', 'hirvapatel7', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(99, 'Mardav Oza', 'Nisarg Rajpura', 'mardavoza@yahoo.in', 'SherLocked', 7229011998, 'GCET', 'Sim@720@tronics', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(100, 'Vaibhav', 'Ajinkya', 'ajmajinkya06@gmail.com', 'Team no. 1', 9422985449, 'DAIICT', 'qwerty123', 'Mitron', 'Tokyo', 'LGBTQ Equality at the Fortune 500 Magazine', ' new HPI 1/10 4WD desert trophy truck', 'Kerala Blastards', 'The Outlaw Josey Wales', '14/02/2017', 'A house is made of wood and stone, but only a  wom', 'June', 'TNT', 'Steven Sasson', 'Pankaj Advani', 'Lamborghini Aventador S: A Powerful Beast', '2011', 'Nintendo', 'Kaahani 2', 'Ultrasonic', 'The New San Juan City Hall', 'Spice Girls', 'Shakesphere', 1),
(101, 'Deep Tandel', 'Dhaval Patel', 'deeptandel2010@gmail.com', 'Pentagon', 9624210044, 'DAIICT', 'deepdhaval', 'Mitron', 'Tokyo', 'Northwestern Mutual', 'federer', 'Squire Whipple', 'the good, the bad and the ugly', 'valentine''s day', 'Necessity, not Scarcity, is the Mother of Inventio', 'june', 'When Angels Cry', 'thomas edison', 'england', 'Mighty morphin', 'SEAL Team 6', 'Pokemon', 'u r my jaan', 'gene hackman', 'San Andres', '', '', 0),
(102, 'nidhi makwana', 'parthvi vala', 'parthvi.vala@gmail.com', 'cumberbatched', 8460512677, 'gec bhavnagar', 'paronidhi221b', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(103, 'Mohit Agrawal', 'Arun Kumar Singh', 'agrawalmohit211@gmail.com', 'Sher Singh', 9638508951, 'V.G.E.C.', 'shersingh', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(104, 'Riya Shah', 'Pankti Shah', 'rhshah171198@gmail.com', 'Smartinis', 9427938080, 'DA-IICT', 'Rhs@1998', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(105, 'Manan Patel', 'Hirva Patel', 'patelmanan222@gmail.com', 'M_locked', 9409668841, 'G H Patel College Of Engineeri', 'hirvapatel7', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(106, 'Dolly Modha', 'Hardik Vora', 'modhadolly@gmail.com', 'Omniscient', 8460528871, 'V.V.P', 'canada2177', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(107, 'Suresh', 'Pavan', 'Himymfan005@gmail.com', 'SH', 9558836009, 'Daiict', 'Himymfan005@gma', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(108, 'chirag darji', 'anil sanghani', 'anilsanghani75@gmail.com', 'pattern finder ', 7878337747, 'daiict', 'anil1729', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(109, 'Dhruman Daxini', 'Noone', '201301050@daiict.ac.in', 'JustTry', 9624041498, 'DA-IICT', 'faltu1234', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(110, 'Dhaval Prajapati', 'Aayush Kapadiya', '201401138@daiict.ac.in', 'D_A', 7698708325, 'DA-IICT', '12345678', 'Yousuf Malala and Satyarthi', 'Greece', 'Benhur Samson', 'M S Dhoni', 'Federal Territory Day', 'The Good, the Bad and the Ugly', '14th February 1990', 'Dimag ki batti jalao', 'June', 'Burning man', 'Thomas Alva Edison', 'Ravindra Jadeja', 'Rolls Ray', '2014', 'Counter Strike', 'Kahani', 'NULL', 'NULL', 'NULL', 'Vishal Bhardwaj', 1),
(111, 'lokesh jigalur', 'udit shrivastava', '201611029@daiict.ac.in', 'T2', 7046997006, 'DA-IICT', 'Lok@2esh', 'NULL', 'statue of liberty', '50 shades of grey', 'Roger federer', 'convocation', 'The Good, the bad and the ugly', '14th february', 'toomany desires harm the mind; to desire too much ', 'June', 'Electric six', 'thomas alva edison', 'krun Nair', 'mustang', '2011', 'Super Mario', 'Ram teri Ganga mali', 'NULL', 'NULL', 'NULL', 'shakespear', 1),
(112, 'Chahak Mehta', 'Rahul Saranjame', 'chahakcr7@gmail.com', 'Hail Siranjame', 7383689577, 'DA-IICT', 'bloodofolympus', 'Vibrant gujarat', 'Japan', 'Tim Cook', '21-31-50-51-69', 'Bharat Ratna', 'The good, the Bad and the Ugly', '14 feb', 'Necessity is the mother of invention', 'June', 'ACDC', 'Edison', 'Battle of Thermopylae', 'Isuzu V max D cross', '2011', 'Mario', 'Madhavikutty ', 'Sonic DX', 'Bermuda triangle', 'Team rocket won against ash', 'Shakespeare', 1),
(113, 'Rahi', 'Anamika', 'shethrahi@yahoo.com', 'inky777', 8758593304, 'DAIICT', 'anamika_rahi', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(114, 'Prachi ', 'Nishtha', 'prachi.palor15@gmail.com', 'Shinning stars', 9727066714, 'DA-IICT', 'PR@CHI15', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(115, 'Darsh Vajaria', 'Tirth Engineer', 'darshvajaria@gmail.com', 'Tirsh', 7228899400, 'DAIICT', '@#LOVE', 'NULL', 'NULL', 'Tim cook', 'Yannick Noah', 'Sam Bahadur', 'The good bad and the ugly', 'Ryan kirkpatrick', 'Necessity is mother of invention', '21 June', 'Vulkano', 'Thomas edison', 'Azhar Ali', 'NULL', '2011', 'wii sports', 'Ram teri ganga meli', 'Drosophila embryogenesis', '', '', '', 0),
(116, 'Dori Divya . P', 'Richa Shah', 'divyadori@gmail.com', 'clamsy', 9825804731, 'vvp engineering college', 'paritosh3420', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(117, 'Prithvish Doshi', 'Meet Sinojia', 'prithvishdoshi1710@gmail.com', '#Sherlocked', 7226043053, 'DA-IICT', 'prd@171098@', 'NObel Prize for Physics 2016 divided in two parts', 'Tokyo', 'Sandeep and Kartik', 'YG Winner', 'Sachin fixing nuts and bolts of a BMW car engine', 'The Outlaw Josey Wales', 'Colorado plane crash', 'NULL', 'June', 'TNT Band', 'Steven Sasson', 'NULL', 'Trini Kwan', '1886', 'Pokemon GO', 'The Dirty Picture', 'NULL', 'City of San Juan', 'NULL', 'William Shakespeare', 1),
(118, 'Saloni Amipara', 'Kinal Kakkad', 'amiparasaloni.as@gmail.com', 'challengers', 8460808247, 'vvp engineering college', 'salonivvpkinal', 'modi won two noble prize', 'statue of zeus', 'tim cook', 'NULL', 'NULL', 'NULL', '14 February ', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(119, 'Chavda Megha', 'Pillai Aishwarya', 'aishwarya97mohan@gmail.com', 'stars', 9909916294, 'v.v.p engineering college', 'achumeghu', 'nobel victory', 'france', 'NULL', 'Tim cook', 'NULL', 'James bond', '14 -02-2017', 'an empty mid is a devils workshop', 'NULL', 'explosion', '', '', '', '', '', '', '', '', '', '', 0),
(120, 'Havya Panchal', 'Kishan Radia', 'hkpanchal1998@gmail.com', 'Heroes and Zeros', 9512410530, 'DA-IICT', 'password', 'Mitron', 'rio', 'fortune global 500', 'Virat kohli', 'Convocation', 'high plains drifter', '26 march 2015', 'The shape of things to come', 'June', 'TNT', 'Thomas Alva Edison', 'Saurav Ganguly', 'Vespa', '', '', '', '', '', '', '', 0),
(121, 'Mit Vasani', 'Bishesh Oram', 'vasanimit9@gmail.com', 'Ross Specter', 9409014354, 'DA-IICT', 'thebisheshist', 'PM Modi inaugurating nobel prize exhibition in ahm', 'Tokyo', 'Tim Cook', 'Roger Federer', 'Possibility of Sachin Tendulkar getting a knightho', 'NULL', 'Virat Kohli getting out in the semi final of icc c', 'Brainfuck language', 'World Yoga day', 'AC/DC', 'Swades was voted best motion picture', 'Sachin''s 200 against South Africa at  Gwalior 2010', 'People having depersonalization disorder', 'Prince William aginst animal trafficking in south ', 'Mario', 'Kanoon', 'Sonic hedgehog', 'Bermuda triangle', '', '', 0),
(122, 'Mitul Sorathia', 'Jay Lodhiya', 'mitulsorathia@gmail.com', 'Pop 7', 9727529477, 'V.V.P Engineering College', 'sunshine', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(123, 'Mohit Kavathiya', 'Bhavik Sampat', 'bhavikbhatia65@gmail.com', 'Mob 7', 9586477977, 'V.V.P Engineering College', 'sunshine', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(124, 'Brijen Sankhavara', 'Nisarg Fasra', 'brijensankhavara@gmail.com', 'Bri 7', 8238282653, 'V.V.P Engineering College', 'sunshine', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(125, 'Rohan Dhanwani', 'Chirag Poddar', 'rohandhanwani@gmail.com', 'The Daemons', 8460435249, 'DA-IICT', 'rohanchirag', 'demonetisation', 'statue of unity', 'LGBTQ Equality', 'Wimbledon(Lawn Tennis) grand slam', 'bharat ratna', 'ELI WALLACH(the good,bad and the ugly ; lee van cl', '14 february', 'karen vaswani(canonisation of mother teresa)', '21 june(international yoga day)', 'porphyrin(TNT meisenmer complex)', 'thomas alva edison(vote recorder,bulb,motion pictu', 'knighthood', 'Julie Williams(During the XBorg attack on the plan', 'Events in 2011(Osama bin laden execution,south sud', 'Pokemon Go', 'tumhari sulu', 'Sonic the hegdehog', 'USA(miami,san juan,puerto rico', 'kitty genovese', 'shakespeare', 1),
(126, 'Shivani Bhandari', 'Jainil Pariya', 'bhandari.shivani16@gmail.com', 'Legendary', 7485917450, 'DA-IICT', 'thecatatetherat', 'NULL', 'Tokyo', 'Brendan Eich', 'NULL', 'M. Visvesvaraya', 'The good, the Bad and the Ugly', 'February 14', 'Necessity is the mother of invention', 'June', 'Thunderstorm', 'Thomas Alva Edison', 'Ravindra Jadeja', 'Force', '2011', 'Nintendo', 'The Dirty Picture', 'Genesis', '', '', '', 0),
(127, 'Bhavya Shah', 'Hemant Goyal', 'bhavyashah777.bs.bs@gmail.com', 'Team_Moriarity', 9428565941, 'VGEC', 'mindpalace41', 'NULL', 'NULL', 'Fortune 500', 'NULL', 'Bharat Ratna', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(128, 'Dhrumil Patel', 'Jaimin Chaudhari', 'dbpatel29699@gmail.com', 'Holmesbrother', 9904079035, 'DAIICT ', '9429538592', 'Vibrant Gujarat global Summit ', 'Tokyo,japan', 'Indian oil', 'NULL', 'NULL', 'Greater Glory', '6 july 2013', 'NULL', 'June', 'raise hell', 'jacob myers', 'NULL', 'NULL', '', '', '', '', '', '', '', 0),
(129, 'Vishwa Sheth', 'Jinal Rabadiya', 'shethvishwa3@gmail.com', 'Mystery_breakers', 9099736457, 'DA-IICT', 'jinalR', 'Sweden''s prime minister in General Assembly of UN.', 'Beijing Olympics 2008', 'Tim Cook', 'NULL', 'FTC 7314 build in september 2014 DEW Robotics', 'NULL', '15th feb 2017', 'NULL', 'June', 'Hell band', 'NicÃ©phore NiÃ©pce', 'NULL', 'NULL', '2011', 'Video game', 'NULL', 'NULL', 'NULL', '', '', 0),
(130, 'Sulay Shah', 'Akshat Gautam', 'sulay15399@gmail.com', 'DA-ngal', 8452056646, 'DA-IICT', 'sasukechutiya', 'Malala', 'Mount Rushmore', 'Tim Cook', 'John Isner', 'Mokshagundam Visvesvaraya', 'The Good, the Bad and the Ugly', '14th February', 'Idle Mind Is A devil''s Workhouse', 'June', 'Tell No Tales', 'Edison', 'Sehwag', 'Thunder Megazord', '2011', 'Legend of Zelda', 'Ramayan', 'Sonic Hedgehog', 'Puerto Rico', 'Pokemon Go', 'Shakespeare', 1),
(131, 'Kritika Gupta', 'Gaurav Sofat', 'kritika29498@gmail.com', 'AreWeThereYet', 9011032739, 'DA-IICT', 'googlockholmes', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(132, 'Harshil Motiyani', 'Mahin Agrawal', 'mahinagr@gmail.com', 'Mindreaders', 7043695855, 'DAIICT', 'mahhar12345', 'narendra modi''s hope for UN nobel peace prize', 'tokyo', 'sundar pichai', 'serena williams', 'knight award day', 'The Outlaw Josey Wales', '14th february', 'NULL', 'june', 'TNT band', 'thomas alva edison', 'karun nair', 'NULL', '2011', 'NULL', 'dirty picture', 'NULL', 'NULL', '', '', 0),
(133, 'Jay Shah', 'Nirmal Patel', 'shahjay147@gmail.com', 'Loosers', 7043531974, 'DA-IICT', 'qwerty', 'NULL', 'tokyo', 'Tim cook', 'Novak Djokovic', 'Mokshagundam Visvesvaraya', 'the good the bad and the ugly', '14/02/1990', 'NULL', 'june', 'Thunderstruck', 'NULL', 'Ravindra Jadeja', 'the beast', '2011', 'super mario', 'kahani', 'NULL', 'NULL', 'NULL', 'william sheckspear', 1),
(134, 'Aditi', 'Kriti', 'kritiu909@gmail.com', 'Powerpuff Girls', 9737777129, 'DA-IICT', 'Kittyu123*', 'NULL', 'Tokyo', 'Tim Cook', 'Andy Murray', 'group captain', 'The good, the bad and the ugly', 'Valentine''s day', 'Charity begins at home', 'June', 'TNT', 'Thomas Elva Edison', 'Sachin ', 'Cadillac', '2011', 'NULL', 'NULL', '', '', '', '', 0),
(135, 'Ravi Babriya', 'Anand Pipaliya', 'ravibabariya11@gmail.com', 'Dream-makers', 8758628542, 'daiict', 'Dream123', 'Narendra Modi''s wish to win Nobel Prize', 'Tokyo,japan', 'Tim Cook', 'M.s.Dhoni', 'Master blaster', 'The Good, the Bad and the Ugly', '14th feb', 'mother teresa had serviced of people ', 'june', 'TNT band, 	Trondheim, Norway', 'thomas edison ', 'Karun Nair', 'bele car', '2011', 'Nintendo', 'Kanoon ', 'NULL', 'NULL', '37 promotion', ' William Shakespeare', 1),
(136, 'Parva Patel', 'Meetrajsinh Vala', 'parvapatel12@gmail.com', 'The Detectives', 7990574509, 'daiict', 'parvameetraj123', 'Stefan lofven', 'Tokyo', 'Brendan Eich', '2002 FIFA World cup', 'Sachin used SS company''s guards while playing cric', 'The good, the bad and the ugly (A movie)', '14th february (Indian plane AIRBUS-320 crashed on ', 'God could not be everywhere and therefore he made ', 'june', 'Overkill band', 'Jacob Myers', 'Sachin Tendulkar', 'Hero Ranger bicycle', '2011', 'Sim city', 'Ghanchakkar', '', '', '', '', 0),
(137, 'Smeet Jani', 'Vismay Malondkar', 'smitjani7@gmail.com', 'flip_FLOP', 7405527210, 'DA-IICT', 'randombinary', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(138, 'Tarun Mavani', 'Shreyansh', 'tarun.11mavani@gmail.com', 'Fab', 8238619010, 'Da-iict', 'qwerty123', 'Kailash Satyarthi and Malala Yousafzai', 'Tokyo', 'Tim Cook', 'NULL', 'Squire', 'The Outlaw Josey Wales', '14 February', 'Food, Clothes and Shelter', 'June', 'TNT', 'Thomas Edison', 'Sehwag', 'NULL', '2011', 'Mario', 'Kanoon', 'DNA', 'Bermuda Triangle', '37', 'William', 1),
(139, 'Vrund Shah', 'Geet Patel', 'vashah14741@gmail.com', 'The Analysts', 9426830425, 'DA-IICT', 'vrund_geet', 'Demonetisation', 'tokyo', 'Tim Cook', 'Manuel Neuer', 'NULL', 'three musketeers', '15 February', 'All work and no play makes Jack a dull boy.', 'June', 'NULL', 'Thomas Alva Edison', 'NULL', 'NImbus 2000', '2011', 'Nintendo', '', '', '', '', '', 0),
(140, 'Sunil', 'Shaleen', 'sunilom.04@gmail.com', 'Stanley', 8980526776, 'DA-IICT', 'morganss', 'vibrantgujarat', 'Tokyo Japan Olympics 2020', 'Tim Cook', 'John Isner. Longest Wimbledon Match', 'Knighthood 23rd april', 'The good, bad and the ugly', 'Valentine''s Day', 'mother teresa', 'June', 'AC/DC', 'Edison', 'NULL', 'NULL', 'NULL', 'Pokemon GO', 'NULL', 'DNA', 'Mauritius', 'Jessi', 'vishal bhardwaj', 1),
(141, 'Enakshi ', 'Shreya Chatterjee', 'enakhi.borse@yahoo.in', 'The Seekers', 9971684074, 'NID', 'nc1p4pdag2', 'demonetisation', 'Tokyo ,Japan', 'The Fortune 500', 'Volkswagen', 'Pope Francis', 'The Good, the Bad the ugly', 'Open relationship', 'Roti Kapda aur makaan', 'Moon Salutation', 'AC/DC', 'george eastman', 'Stuart Broad', 'Range Rover', '2011', 'gameboy', 'ghanchakkar', 'DNA', 'Indonesia', 'ISRO', 'William Shakespeare', 1),
(142, 'Darshan', 'Poojan', 'darshankapadiya89@gmail.com', '123456', 9824643673, 'daiict', '123456', 'Nobel Prize Series, India, 2017', 'NULL', 'NULL', 'SR Watson', 'Valentine''s day', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(143, 'Darshan Patel', 'Umang Patel', 'umangsp.1199@gmail.com', 'Team', 8141450011, 'DAIICT', 'password', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(144, 'Rutul Thakkar', 'Yash Vanzara', 'rutul94@gmail.com', 'Red Devils', 7567292905, 'DAIICT', '7567292905', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(145, 'Ritwik Bharadwaj', 'Tanya Garg ', 'bharadwaj.ritwik@gmail.com', 'Moti and Patlu', 8980210761, 'DA-IICT', '20114251', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(146, '1', '2', '12@12.com', '12', 1212121212, '12122', '121212', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(147, 'Sai Aditya Paruchuri', 'Sumanth Tangirala', 'saiaditya.paruchuri@gmail.com', 'Defective Detectives', 9327554562, 'DA-IICT', 'Heygooglock', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(148, 'SWAPNIL', 'Nilay', 'swapniljethwa22@gmail.com', 'Investigator', 9913701646, 'DAIICT', 'suramya22', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(149, 'Nachiket', 'Sanket', 'nachiket5197@gmail.com', 'East wind', 9687656514, 'DAIICT', 'nvt5197', 'kailash satyarthi', 'tokyo', 'tim cook', 'roger federer', 'sachin''s crusade against cancer', 'the good, the bad and the ugly', 'NULL', 'mother teresa', 'ATV-2', 'nitrogen cycle', 'swades', 'NULL', 'tommy', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 1),
(150, 'Bhavesh Khatnani', 'Rishikesh Bhatt', 'bhaveshkhatnani611@gmail.com', 'Akatsuki', 7041038583, 'DA-IICT', 'b00611k', 'Demonetization', 'tokyo tower', 'Tim cook', 'NULL', 'NULL', 'outlaw josey whales', '2016', 'Cash is King', 'Connect the Youth', 'welsh band', 'NULL', 'NULL', 'Ford Ranger', 'NULL', '', '', '', '', '', '', 0),
(151, 'Ayush Patel', 'Digant Chaudhary', '201301089@daiict.ac.in', 'BabaYaga', 9033019378, 'Da-iict', 'daiict', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(152, 'Nirav Dobariya', 'Krit Patel', 'dbnirav007@gmail.com', 'The Legends', 7096551572, 'DA-IICT', '123456789', 'UNSHARED SUCCESS IS FAILURE', 'TOKOYO', 'INDRA NOOYI', 'NOVAK DJOKOVIC', 'International Human Solidarity Day ', 'The Outlaw josey Wales', '14 FEBRUARY', 'NULL', 'JUNE', 'EARTH, WIND & FIRE', 'THOMAS ALVA EDISON', 'Usain bolt', 'NULL', '2011', 'MONOPOLY', 'kahani @', 'DNA', '', '', '', 0),
(153, 'Urvish', 'Mounish ', 'urvishprajapati36@gmail.com', 'Morvish', 7359797474, 'Silver Oak college of technolo', 'urvish123', 'Linus Pauling', 'tokyo', 'tim cook', 'john isner', 'NULL', 'the good bad and ugly', 'valentine day', 'NULL', 'june', 'NULL', 'Thomus A edition', 'Azhar Ali', 'NULL', '2011', 'super mario', 'ram teri ganga maili', 'NULL', '', '', '', 1),
(154, 'Miral shah', 'Biraj mithani', 'miralshah365@gmail.com', 'sneaky slammer', 9558622732, 'vvp engineering ', 'miral95586', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(155, 'Nirav Alpesh Shah', 'Shaival Shah', 'shahniravalpesh@gmail.com', 'NS', 9879705900, 'Charusat', 'asdfghjkl', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(156, 'Nikita Chhatbar', 'Shivani Shah ', 's.shah2456@gmail.com', 'Sassy girls ', 9824279119, 'V.V.P. Engineering College', 'vvp123', 'demonitization', 'beijing', '500 LGBT syndicate', 'Winbledon Championship', 'NULL', 'NULL', 'breaking news', 'NULL', 'international yoga day', 'bhopal gas tragedy', 'elections', 'victory', 'NULL', 'kiss to death', 'smart devices', '', '', '', '', '', 0),
(157, 'Chintan', 'Ajay', 'chintan.ramanuj@gmail.com', 'Wolves of da', 9586899933, 'DA-IICT', 'csr303', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(158, 'Yash Patel', 'Meet Patel', 'yashapatel786@gmail.com', 'YAP786', 7359485829, 'DAIICT', 'YAP786', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(159, 'Mayur detroja', 'Devansh gohil', 'Devgohil102@gmail.com', 'The_a_team', 9904621039, 'Da-iict', 'backchod123', 'NULL', 'Egypt', 'apple', 'winner', 'Visvesvaraya', 'the good the bad and the ugly', 'Valentine day', 'Necessity not Scarcity', 'june', 'dynamite', 'NULL', 'Thomas Alva Edison', 'NULL', '2011', 'clash of clans', 'bhul bhulaiyaa', 'speed', 'NULL', 'NULL', '', 0),
(160, 'Neel Chaudhary', 'Solanki Ketul', 'neelchaudhari51097@gmail.com', 'JOKER', 7984069616, 'DA-IICT', 'neelketul', 'Noble Prize series', 'NULL', 'Asana', 'time management for success', 'M. Visvesvaraya', 'true grit', '14 feb valentine day', 'NULL', 'june', 'AC/DC', '', '', '', '', '', '', '', '', '', '', 0),
(161, 'Patel Naishal', 'Vivek Gover', 'naishal1499@gmail.com', 'Brain Stormers', 9099039943, 'DAIICT', 'naishal@123', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(162, 'Dangar', 'PK', 'eagle11061997@gmail.com', 'Loaders', 8160047030, 'Fuck you', 'md1161997', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(163, 'Jayraj Kachariya', 'Parth Patel', 'jayraj.kachariya.175@gmail.com', 'Aghori Brothers', 8866318949, 'DA-IICT', 'fuckthatshit', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(164, 'Jinal', 'Pinal', 'jinalparikh410@gmail.com', 'J_P', 7359105720, 'DAIICT', 'shreeji', 'Malala Yousafzai and Kailash Satyarthi', 'Tokyo', 'NULL', 'Andy Murray', 'Sir Mokshagundam Visvesvaraya(Visvesvaraya Iron & ', 'The Good, the Bad and the Ugly', '14 February ', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(165, 'Abhishek Patel', 'Akshat Patel', 'adpatel3697@gmail.com', 'Deadlockers', 8866628217, 'DAIICT', '1237896540', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(166, 'Vaishnav Vishal', 'Mayank Maurya', '201451051@iiitvadodara.ac.in', 'Atsob', 7874629669, 'IIIT Vadodara', 'Vishalmsd7', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(167, 'Prakruthi Pule', 'Anandita Agrawal', '201614008@daiict.ac.in', 'Hawks', 7486801399, 'Dhirubhai ambani university', 'Bunny1234', 'd', 'barbados', 'sushil kumar', 'NULL', 'gladiator', 'guru', '1929', 'idecipher', '21st june', 'nuclear blast/ hell', 'Thomas Edition', 'gladiator', 'zord', '2011', 'android', '', '', '', '', '', 0),
(168, 'Anuj Bhavsar', 'Parth Vaghela', '201401133@daiict.ac.in', 'Suits', 9426682544, 'DA-IICT', '1122334455', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(169, 'Manthan Soriya', 'Parshwa Shah', 'manthansoriya9183@gmail.com', 'SuperBatman', 7778889980, 'DA-IICT', 'g207g207', 'Peace and Noble', 'Forbidden city', 'Fortune global 500 2014', ' it''s six o clock', 'Master Blaster in shining armour', 'South America', 'Trending and shocking discovery', 'We need brain for fulfilling basic need of humans', 'June ', 'Bomb blast tnt', 'India ', '511', 'powerful woman', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 1),
(170, 'Umang Panchal', 'Maulik Bopalia', 'umang.panchal61@gmail.com', 'Jesters', 9427457298, 'DA-IICT', '12345678', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(171, 'Dveep Chaudhari', 'Harmish Ganatra', '201501172@daiict.ac.in', 'Holmes', 8690030352, 'DAIICT', 'harmishtaapu', 'kailash satyarthi', 'Tokyo', 'Tim Cook', 'John Isner', 'M. Visvesvaraya', 'The Good, the Bad and the Ugly ', '14th february', 'Necessity is the mother of invention', 'June', 'TNT coverband', 'Thomas Edison', 'usain bolt', 'range Rover', '2011', 'NULL', 'ram teri ganga meli', 'NULL', 'NULL', 'pslv c 37 rocket launch', '', 0),
(172, 'Milan', 'Nisharg', '201601102@daiict.ac.in', 'the#', 8866977080, 'DA-IICT', 'mini96102', '25/09/2015', 'Tokyo', 'Marc Benioff', 'Turkish cup', 'Mokshagundam Visvesvaraya', 'The Good, the Bad and the Ugly', '14 february', 'NULL', 'June', 'TNT band', 'Thomas Edison', 'Virendra Sehwag', 'NULL', 'Counter Strike', '', '', '', '', '', '', 0),
(173, 'brijesh', 'pratik', 'brijeshpanara24@gmail.com', 'qwerty', 9033403367, 'da-iict', 'qwerty123', '25 september 2015', 'NULL', 'tim cook', 'Ricky Ponting', 'M. Visvesvaraya', 'cowboys', '14 feb', 'painter bud', 'june', 'the chainsmokers', 'Thomas Edison', 'shewag', 'NULL', '2015', 'NULL', '', '', '', '', '', 0),
(174, 'Rishabh', 'Avan', 'avanrishabh7@gmail.com', 'D-flash', 9979185893, 'DAIICT', 'google@7', 'NULL', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(175, 'Kritika Somani', 'Khushboo Chandwani', 'skritika20@gmail.com', 'A team', 8141246869, 'DA-IICT', 'Kritika869#', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(176, 'Paras rangani', 'Shivangi mehta', 'parasrangani@yahoo.com', 'Team paras', 7779000075, 'V.V.P engineering college', 'paraspatel', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(177, 'Shruti', 'Komal', 'shrutis1051@gmail.com', '402', 9537160842, 'DAIICT', 'VipulGreens', 'NULL', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(178, 'Umang', 'Mithil', '201401096@daiict.ac.in', 'Team Name', 9426166536, 'DA-IICT', '12345678', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(179, 'Kathan Vaidya', 'Vivek Chavda', 'vaidyakathan12@gmail.com', 'MIGHTY MINDS', 7600652347, 'DA-IICT', 'kv121314', 'Linus pauling', 'Tokyo', 'Tim Cook', 'NULL', 'Napoleon', 'the good the bad and the ugly ', '14 Feb', 'NULL', 'Junius(June)', 'TNT band', 'Thomas alva edison', 'NULL', 'NULL', '2011', 'NULL', '', '', '', '', '', 0),
(180, 'Kavan Patel', 'Nihal Satbhai', 'kavanpatel2403@gmail.com', 'ELIMINATORS', 8320428751, 'DA-IICT', 'jaychehar', 'linus pauling', 'tokyo', 'NULL', 'M s DHONI', 'Mokshagundam Visvesvaraya', 'the good and the bad and the ugly', '14 FEBRUARY', 'â€œNot all of us can do great things. But we can d', 'JUNE', 'TNT BAND', 'THOMAS ALVA EDISON', '', '', '', '', '', '', '', '', '', 0),
(181, 'Harshit Bhut', 'Maulik Trapasiya', 'harshitbhut14@gmail.com', 'Sherlock homes', 9408610670, 'DA-IICT', 'we will win', 'NULL', 'tokyo', 'tim cook', 'wimbledon', 'World Cancer Day', 'The Man Who Shot Liberty Valance', '14 february', 'mother mind money', 'June', 'TNT', 'thomas alva edison ', 'Efren Reyes', 'beauty and the beast', 'NULL', 'NULL', 'ramayana', 'Gene Hackman ', 'NULL', 'closer', 'william shakespeare', 1),
(182, 'Parth', 'Utsav', '201301098@daiict.ac.in', 'TeamEuros', 9712916367, 'DA-IICT', '123456789', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(183, 'Sreeraj R', 'Rahul Rathore', 'srpillai88@gmail.com', ' Oozma kappa', 7436069618, 'DAIICT', 'oozmakappa', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(184, 'Shrey Shah', 'Nisarg Patel', 'patel321nisarg@gmail.com', 'Some generic name', 9925158748, 'DA-IICT', 'roshanshah', 'Linus Pauling', 'Tokyo,Japan', 'Tim Cook', 'christopher katongo', 'M. Visvesvaraya', 'Good,the bad and the ugly', '14/02/2017', 'Necessity is the mother of invention', 'June', 'Thunderstorm Band', 'Thomas Alva Edison', 'virender sehwag', 'BMw', '2001', 'Mario', '', '', '', '', '', 0),
(185, 'FALDU HAPPY', 'SUDANI KRISHNA', 'happyfaldu1704@gmail.com', 'FEARLESS ', 9427385645, 'vvp', 'patelks123', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(186, 'jhanvi makwana', 'kruti makadiya', 'makjhanvi@gmail.com', 'brainstomers', 8758525629, 'vvp engg college', 'jhanvikruti', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(187, 'Aviral', 'Rajiv', '201301178@daiict.ac.in', 'bhaktabhakt', 8511598537, 'DAIICT', 'googlock', 'nobel prize exhibition', 'Tokyo', 'Tim Cook', 'Andy Murray', 'NULL', 'The good, the bad and the ugly', '14th February', 'Mother Teresa Foundation', 'NULL', 'NULL', 'kutto k bacho.', 'Bombardier Dash 8', 'Mighty Morphin Power Rangers. ', '2011', '', '', '', '', '', '', 0),
(188, 'Varsani Bansi', 'Shah Nikita', 'bansi.varsani88@gmail.com', 'BRAIN TWISTER', 7069858054, 'vvp', 'shah123', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(189, 'Adit Shah', 'Harsh Vyas', 'aditshah231998@gmail.com', 'Nobody', 7383441771, 'DA-IICT', 'Adit@231998', 'kailash satyarthi', 'tokyo', 'tim cook', 'wimbledon', 'vishveshwarya', 'The Good, the Bad and the Ugly', 'Valentines day', 'Necessity is the mother of invention', 'june', 'TNT band', 'thomas edison', 'azhar ali', 'audi', '2011', 'gta 5', 'ram teri ganga maili', 'angry birds', 'horror', 'pokemon go', '', 0),
(190, 'Abhishek Sinha', 'Vrunda Bhalodi', 'abhisheksinha072@gmail.com', 'simply_smart', 9537938956, 'V.V.P Engineering College', 'agitation123', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(191, 'Aarsh Sheth', 'Himanshu Vardhan', '2016140092@daiict.ac.in', 'Moriarty', 8141055638, 'DA-IICT', 'missme?', 'Kailash Satyarthi', 'japan', 'tim cook', 'Kim Hyeon-woo', 'NULL', 'The Good Bad And Ugly', 'Feb 8, 2016', 'NULL', 'june', 'AC/DC', 'Thomas Edison', 'NULL', 'Range Rover', 'NULL', 'NULL', 'Kahani', 'NULL', 'NULL', 'NULL', '', 0),
(192, 'Keval Dave', 'Milit Panchasara', 'kevaldawe@gmail.com', 'Mind Bogglers', 7016670487, 'DA-IICT', '*25#KevalD', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(193, 'Drashti Shah', 'Heli Shah', 'heliparesh@gmail.com', 'Calvin-Hubs', 9408783982, 'DA-IICT', 'helishah', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(194, 'Mihir Gajera', 'Shirish Jain', 'mihirgajera1@gmail.com', 'Gooooogler', 9913543593, 'DAIICT', 'damilushiru', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(195, 'DHAMI RENA', 'GAJERA MIRAL', 'renadhami97@gmail.com', 'ROCK AND ROLL', 8140196171, 'VVP', '777rena', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0);
INSERT INTO `login` (`id`, `name1`, `name2`, `email`, `team_name`, `mobile`, `college`, `password`, `q1`, `q2`, `q3`, `q4`, `q5`, `q6`, `q7`, `q8`, `q9`, `q10`, `q11`, `q12`, `q13`, `q14`, `q15`, `q16`, `q17`, `q18`, `q19`, `q20`, `lastq`) VALUES
(196, 'Karan Jain', 'Smit Shah', 'karanjn619@gmail.com', 'Aztecs', 9913999113, 'DA-IICT', 'Aztecs123', 'Nobel Peace Prize', 'Tokyo', 'Fortune 500', 'Novak Djokovic', 'Knighthood award for sachin tendulkar', 'the good, the bad and the ugly', 'Bangalore', 'No greater love', '21st June', 'AC/DC songs', 'Thomas Alva Edison', 'Virender Sehwag', 'emma goodfall', '2011', 'super mario', 'mahabharat', 'sonic hedgehog(shh gene)', 'NULL', 'meitu', 'william shakespeare', 1),
(197, 'Roshani', 'Purva', 'purvamhasakar@gmail.com', 'Digital Fortress', 7433053793, 'Daiict', 'holmes', 'Demonetisation', 'Tokyo,Japan', 'Fortune companies', 'Diamondbacks', 'M. Visvesvaraya', 'The Good, the Bad and the Ugly', '14 February', 'NULL', 'June', 'NULL', 'Thomas Edison', 'NULL', '', '', '', '', '', '', '', '', 0),
(198, 'pradip karnavat', 'kadam patel', 'pkadam9744@gmail.com', 'path_finder', 8154849157, 'DAIICT', '789Kadam@', 'vibrant gujarat', 'tokyo,japan', 'filpkart', 'NULL', 'NULL', 'smoke doesnt get in your eyes in biopic  of jackki', 'ex taraba governer', 'dhiraj kumar', 'NULL', 'NULL', 'NULL', 'NULL', '2017 movies', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 1),
(199, 'Yash Patel', 'Karan Pardasani', '201601464@daiict.ac.in', 'Code Crackers', 7874527842, 'DAIICT', '464466', 'NULL', 'Portugal', 'Tim Cook', 'NULL', 'NULL', 'The Good the Bad and The Ugly ', '14 February', 'We think sometimes that poverty is only being hung', 'June', 'Linkin Park', 'Thomas Alva Edison', 'Sania Mirza', 'Time', '2011', 'NULL', '', '', '', '', '', 0),
(200, 'Adit Patel', 'Nimesh Kalathiya', 'aditkpatel318@gmail.com', 'Genius', 8140672204, 'DA_IICT', '258221', '2 Noble prices are specific', 'Pyeongchang', 'Tim Coo', 'car volkswagen trophy series 2 : 11.5', 'India is celebrating Engineers Day remarkable trib', 'The Outlaw Josey Wales', '14th February ', 'All work and no play makes Jack a dull boy', 'June', 'White Lightning (band)', 'thomas edison', '8 times highest Test match score were done when an', 'power rangers jungle fury', '2012', 'The Legend of Zelda', 'The Dirty Picture', 'NULL', 'NULL', 'Motto ZespoÅ‚u R', 'William Shakespeare', 1),
(201, 'Ganeshsai Garikipati', 'Rohit Mallavarapu', 'saigameplay15@gmail.com', 'BLANK', 7036836804, 'DA-IICT', 'Srcmtmk@1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(202, 'Aditya Raj', 'Akshay Bhamare', 'adi7raj93@gmail.com', 'DA_suplex@city', 7043915207, 'DA-IICT', 'Password8#', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(203, 'Abhishek Padariya', 'Jaykishan Parmar', 'abhishekpadariya@gmail.com', '_QWERTY_', 9537741465, 'DA-IICT', '07051306', 'PM Narendra Modi Inaugurates Nobel Prize Exhibitio', 'NULL', 'Tim Cook', 'india won 2011 cricket worldcup', 'Sir, M. Visvesvaraya (Knight commander) won bharat', 'The Good, the Bad and the Ugly', '14 February', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(204, 'Rajan Pipaliya', 'Maulik Trapsiya', 'rajandp36@gmail.com', 'RajMauli', 8141081381, 'DA-IICT', '123456', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(205, 'Sankalp Ranade', 'Abhilash Mandaliya', 'ranadesankalp@gmail.com', 'Geek Gods', 8401869661, 'DA-IICT', 'sankalp2611', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(206, 'Kush Patel', 'Luv Patel', 'kushhotshot250@gmail.com', 'THUG BROTHERS', 8141230077, 'DA-IICT', 'dalk@2412', 'Linus Pauling', 'tokyo', 'Tim Cook', 'NULL', 'Mokshagundam Visvesvaraya', 'The Good, The Bad and the Ugly', '14 February', 'NULL', 'june', 'AC/DC', 'Thomas Edison', 'NULL', 'NULL', '2011', 'super mario', 'NULL', '', '', '', '', 0),
(207, 'Arpit Patel', 'Bhargav Divakar', '201601036@daiict.ac.in', 'SH1', 7203939741, 'DAIICT', 'sherlock', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(208, 'Jay Patel', 'Dishant Trivedi', 'jay13698@yahoo.com', 'Starboys', 9429759539, 'DA-IICT', '1361998Jay', 'Linus Pauling', 'Japan', 'Tim Cook', 'Serena Williams', 'NULL', 'Dirty Harry', '14 February', 'NULL', 'June', 'Lightning Bolt', 'NULL', 'Ravindra Jadeja', 'NULL', '2010', 'super Mario', 'Kahani', 'Sonic', 'NULL', 'Paris', 'william shakespearre', 1),
(209, 'Mili shah', 'Hiloni mehta', 'Milishah45@gmail.com', 'Googlocked', 9428059445, 'Vvp engg', 'sherlock', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(210, 'Nidhi Gupta', 'Mudra Desai', 'desaimudra50@gmail.com', 'Stark', 9409406396, 'DAI_ICT', 'mudrads13@', 'Demonetisation', 'Tokyo', 'Tim Cook', 'Louisville', 'Visvesvaraya', 'The Good, the Bad and the Ugly ', '14 February', 'necessity is the mother of invention', 'June', 'TNT', 'Thomas Edison', 'Virendra sehwag', 'ambassador', '2011', 'Sonic Dash', 'Mohenjo Daro', ' GJB2', '', '', '', 0),
(211, 'Shivam Agarwal', 'Vaishvik Chaudhary', '201601062@daiict.ac.in', 'Immortals', 7433064095, 'DAIICT', '123456', 'NULL', 'Tokyo', 'Tim cook', 'andy murray', 'visvesvaraya', 'The Good, the Bad and the Ugly', '14 feb', 'NULL', 'june', '', '', '', '', '', '', '', '', '', '', '', 0),
(212, 'smit modi', 'umang parmar', 'sjmodi1997.sm@gmail.com', 'conan', 8460625107, 'DAIICT', 'sonu1997', 'Dr Ambedkar', 'Tokyo', 'Tim Cook', 'Roger Federer', 'Mokshagundam Visvesvaraya', 'The Good, the Bad and the Ugly', ' 14 February 1990', 'Imagination is more important than knowledge', 'June', 'Julius Wilbrand', 'Gustaf de Laval', 'Ravindra Jadeja', 'The Beast', '2011', 'Super Mario', 'Kahaani', 'Sonic', 'Burmuda Triangle', 'Youtube', 'William Shakeshphere', 1),
(213, 'Jeel', 'Rahul', 'jeelprajapati18698@gmail.com', 'Warriors', 9904942170, 'DAIICT', 'abc@123', 'UNHCR', 'Abu Dhabi', 'reliance', 'Chennai Super Kings', 'Sir Arthur Conan Doyle', 'The Good, The Bad and The Ugly', 'Indian Airlines Flight 605 crash', 'Roti Kapda aur makaan movie hair stylist', 'June', 'ACDC band', 'Thomas Alva Edison', '', '', '', '', '', '', '', '', '', 0),
(214, 'Parth', 'Priyank', 'parthdadhania384@yahoo.com', 'Sherlock', 7600014164, 'DA - IICT', 'pd@141198', 'Kailash Satyarthi', 'Tokyo', 'Tim Cook', 'Novak Djokovic', 'M. Visvesvaraya', 'The Good, the Bad and the Ugly', '14th February ', 'Necessity is the mother of invention', 'June', 'TNT', 'Thomas Alva Edison', 'Luis Suarez ', 'Car', '2011', 'The Legend of Zelda', 'The Dirty Picture', 'Genesys', '', '', '', 0),
(215, 'Neelanshi Varia', 'Akshit Soni', 'neelanshiV2@gmail.com', 'DoubleZeroes', 9913304142, 'DA-IICT', 'akshitsoni', 'Vibrant Gujarat', 'Tokyo', 'Tim cook', 'Roger Federer', 'Mokshagundam Visvesvaraya', 'The Outlaw Josey Wales', '14th feb', 'Early to bed, early to rise, makes a man healthy, ', 'june', 'AC/DC', 'Thomas Edison', 'ravindra jadeja', 'NULL', '2011', '', '', '', '', '', '', 0),
(216, 'Jalansh Munshi', 'Abhi Ratnman', 'jalansh.munshi1366@gmail.com', 'Juggernaught', 9173803414, 'DAIICT', 'abhijalansh', '"The Nobel Prize: Ideas changing the world" held a', 'The Golden Pavilion in Japan', 'Apple CEO Tim Cook', 'NULL', 'Mokhshagundam Visvesvaraya', 'Once upon a time in the west', '8/2/2015', 'an apple a dfay kkeeps the doctor away', 'June', 'ACDC', 'Thomas Edison', 'NULL', '', '', '', '', '', '', '', '', 0),
(217, 'Dimple Dodia', 'Bhawana Jaloria', 'dodia123.dd@gmail.com', 'Scorpians', 7405929748, 'DA-IICT', 'dodia123', 'The Nobel Prize: Ideas Changing the World was inau', 'tokyo tower', 'Tim Cook became the first openly gay CEO ', ' Avril Riordan-Cup No. 121 - Perpetual Challenge C', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(218, 'Sonal Damor', 'Digma Patel', 'sonaldamor1996@gmail.com', 'Angels', 9558266755, 'DA-IICT', '9558266755', 'Modi to get alfr nobel prize during UN assembly', 'https://www.google.co.in/imgres?imgurl=https%3A%2F', 'TIM COOK', 'kapil dev', '23 april  sachin''s birthday', 'toy story', '16 january 2017', 'NULL', 'june', 'NULL', '', '', '', '', '', '', '', '', '', '', 0),
(219, 'Pankti Shah', 'Kirtana Phatnani', 'panktibshah@hotmail.com', 'Ambush', 9512979944, 'DAIICT', 'bhaskar', 'Orange is the new black', 'Athens', 'Tim Cook', 'All time Winner', 'M Visvesvarya', 'American Civil war', 'Valentines Day', 'Necessity is the mother of all inventions', 'June 21st- International Yoga day', 'NULL', 'Thomas Edison', 'GS Chappel', 'Range rover', '2011', 'Pokemon go', 'Dirty picture', 'NULL', 'NULL', '2016', 'William shekespeare', 1),
(220, 'shrey mishra', 'dishant rathi', 'shrey.mishra12345@gmail.com', 'gls university ', 8128850100, 'gls university', '8128850100', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(221, 'Premang', 'Savan', '201501063@daiict.ac.in', 'CODEsigneR', 9408231332, 'DA-IICT', 'asdfghjkl', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(222, 'Ekta', 'Drashti', 'ekupatel187@gmail.com', 'VISIONITY', 9726187047, 'DA-IICT', 'Drasht1', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(223, 'Saurav Pratihar', 'Mayur Dangar', 'pratihar.saurav@gmail.com', 'zombie', 9033399314, 'DAIICT', '123456', 'Linus pauling ', 'tokyo', 'tim cook', 'Longest tennis match Wimbledon', 'The Gladiator Poem by Tribhawan Kaul', 'The good, the bad, the ugly-1966', '14 february', 'NULL', 'NULL', 'AC/DC band', 'NULL', 'NULL', 'aston martin', 'NULL', 'NULL', 'NULL', 'NULL', 're', '', '', 0),
(224, 'Guru', 'Hardik Sardhara', 'gg@gmail.com', 'team gay', 9625874121, 'DAIICT', 'gurugay', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(225, 'Riddhi Solani', 'Dhara Kotecha', '201611039@daiict.ac.in', 'angel', 9586290757, 'DAIICT', 'K127RD', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(226, 'Jhanvi makwana', 'Makadiya kruti', 'makjhanvi@gmail.com', 'Rockstars', 7048887742, 'Vvp', 'jhanvikruti', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(227, 'Riddhi Solani', 'Dhara Kotecha', '201611039@daiict.ac.in', 'Angels 127', 9586290757, 'DAIICT', 'K127RD', 'Model United Nations', 'tokyo', 'Doug McMillon', 'NULL', 'M. Visvesvaraya', 'Cowboy', '14th February', 'Necessity is the mother of invention', 'June', 'The Music Explosion', 'thomas Alva Edison', 'Ravindra jadeja', 'NULL', '2011', 'NULL', 'Kahaani', 'NULL', 'NULL', '', '', 0),
(228, 'hardik modi', 'preet sardhara', '201601089@daiict.ac.in', 'freeballers', 9687523781, 'DAIICT', 'h97122@MODI', 'Yoga Day declared by UN', 'THE IMPERIAL PALACE', 'Tim Cook', 'Novak Djokovic', 'M. Visvesvaraya', 'The Good, the Bad and the Ugly', '14 february,1990', 'invention is the mother of discovery', 'June', 'Tell No Tales', 'Benjamin Franklin', 'NULL', 'robot', '2011', 'playstation', '', '', '', '', '', 0),
(229, 'poojan patel', 'dharmin shah', 'poojan210699@gmail.com', 'gls university team', 9974005795, 'gls university', '9974005795', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', 0),
(230, 'omkar', 'aditya', 'omkarvdamle13@gmail.com', 'itselementarywatson', 9724595885, 'DAIICT', 'benedict', 'NULL', 'temple', 'Tim cook', 'novak djokovic', 'Nick Knight', 'The Good, the Bad and the Ugly', 'valentines day', 'necessity is the mother of invention', 'june', 'hell', 'thomas edison', 'brian lara', 'range rover', '2011', 'business', '', '', '', '', '', 0),
(231, 'Abhishek Bhowmik', 'Nilesh Meena', '201601135@daiict.ac.in', 'Alpha-Q', 8133916356, 'DAIICT', 'abhinilesh', 'Kofi Annan', 'tokyo', 'Tim Cook', 'andy murray', 'Visvesvaraya', 'The Good, the Bad and the Ugly', '14 february', 'NULL', 'june', '', '', '', '', '', '', '', '', '', '', '', 0),
(232, 'Tejas Kasundra', 'Malhar Shah', 'kasundratejas111@gmail.com', 'Team Conan', 7228038180, 'DA-IICT', 'tekas@7909', 'Linus Pauling', 'Tokyo', 'Tim Cook', 'Volkswagen AG''s new assembly plant in Chattanooga,', 'M. Visvesvaraya ', 'Dollars Trilogy', '14 February', 'NULL', 'June', 'TNT', 'Joseph Swan', 'pankaj advani', 'zords', '2013', '', '', '', '', '', '', 0),
(233, 'Mohit savaliya', 'Dhruv koshiyar', 'mohitsavaliya111@gmail.com', 'A218', 7048844670, 'DAIICT', '12345678', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'best kisses', 'turn on the speakers', 'hawas badi kutti chizz hoti hai', 'sab moh maya hai', 'black water', 'team rocket', 'movies', 1),
(234, 'Vaidehi', 'Krishna', '201611020@daiict.ac.in', 'Vaidehi', 8980203370, 'DAIICT', 'Vaidehi', 'NULL', 'Tokyo', '500 companies have gay employees ', 'Roger Federer', 'Bharat Ratna winner', 'NULL', 'virat and anushka''s engagement rumour', 'witty graphics', ' june world yoga day', 'TNT heavy metal band', 'Eadweard Muyb', 'Steven Gerrard ', 'zords', '2011', 'NULL', 'kahani2', '', '', '', '', 0),
(235, 'Prapti Trivedi', 'Hetvi', 'prapti.dds@gmail.com', 'iamsherlocked', 9537400137, 'DAIICT', 'athena$19', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'breakup', 'NULL', 'international yoga day', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', '', '', '', '', '', '', 0),
(236, 'Mohamed Shadab', 'Harsh Khatri', 'shadabdragon@gmail.com', 'Team Shady', 9825667234, 'DAIICT', 'qweasdzxc', 'Linus Pauling', 'Tokyo', 'Tim Cook', 'Serena williams', 'April 23', 'West World', '14th Feb', 'Necessity is the mother of invention', '21st june Yoga Day', 'AC/DC ', 'M.B Haneefa', 'Virender Sehwag', 'Jaguar', 'Prince of persia', 'Pokemon', 'Dirty Picture', 'Speed', 'Red Sea', 'Actor rape', 'Shakespear', 1),
(237, 'Saloni Mundra', 'Krishna Manvar', 'salonimundra@gmail.com', 'fruity', 8733065056, 'DA-IICT', 'krishnasaloni', 'Vibrant Gujarat Summit', 'Olympics', 'mozilla', 'Andy Murray', 'M Visveraya', 'Westworld', 'Valentine''s Day(14th February)', 'We think sometimes that poverty is only being hung', 'September', 'AC/DC', ' M. B. Haneefa', 'Karun Nair', 'Segway', '2011', 'super mario', 'Kahaani 2', 'NULL', 'Australia', '', '', 0),
(238, 'shah nilay', 'jethva swapnil', 'shahnilay103@gmail.com', 'barodians', 8347773231, 'daiict', 'nilayswapnil', 'NULL', 'tokyo', 'tim cook', 'roger federer', 'NULL', 'the good,the bad and the ugly', '14 february', 'NULL', 'june', 'thunderstorm', 'thomas edison', 'michel jordan', 'ferrari', '', '', '', '', '', '', '', 0),
(239, 'Ravi Saradava', 'Divyesh Savaliya', 'savaliya.divyesh1722@gmail.com', 'passengers', 8980857230, 'DA-IICT', '172227', 'Malala Yousafzai', 'Tokyo', 'Tim Cook', 'it''s six o clock', 'Bharat Ratna', ' Outlaw Josey Wales', 'February 14', 'Invention', '21 June', 'TNT', 'electronic voting machine', '12', 'power rangers jungle fury', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 1),
(240, 'Akshat Kaneria', 'Dharmil Patel', 'akshat.kaneria@gmail.com', 'The Starks', 9825672300, 'DAIICT ', 'dharmilpatel', 'Model united nations', 'Tokyo olympics 2020', 'NULL', 'NULL', 'Mokshagundam Visvesvaraya', 'The Good, the Bad and the Ugly', '15th feb', 'NULL', 'june', 'The Explosive', 'NULL', 'Virender Sehwag', 'NULL', '2011', '', '', '', '', '', '', 0),
(241, 'Mit Swami', 'Smit Patel', 'mitswami25@gmail.com', 'Nooglers', 8154065492, 'DAIICT', 'asdfghjkl', 'Linus Pauling', 'Tokyo , Japan', 'Tim Cook', 'Aberdeen FC was winner on 11/5/1983(Aberdeen FC vs', 'NULL', 'The good , the bad and the ugly', '14 Feb 2017', 'All work and no play makes Jack a dull boy', 'June', 'TNT', 'Thomas edison', 'NULL', 'porsche', 'june', 'NULL', 'NULL', 'supersonic', 'NULL', 'NULL', 'william shakespeare', 1),
(242, 'kalpit', 'bhavik', 'bhavikmehta98@gmail.com', 'kb', 9925103799, 'DA', '123456', 'Kailash Satyarthi', 'tokyo,japan', 'apple ceo tim cook', 'NULL', 'NULL', 'The Outlaw Josey Wales', '14th Feb', 'NULL', 'June', 'TNT band', '', '', '', '', '', '', '', '', '', '', 0),
(243, 'Aneri Patel', 'Shani Joshi', 'anerivap@gmail.com', 'achievers', 9714245352, 'DAIICT', 'googlockholmes', 'Vibrant Gujarat', 'NULL', 'tim cook and benjamim lin', 'Wimbledon ', 'M V visveseriya who got bharat ratna', 'the good , the bad , the ugly', '15 feb 1961', 'No one cares if you lack in all - beauty,brain and', 'june', 'light the fire', 'Thomas Edison', 'NULL', 'NULL', '2011', 'dr nintendo', 'no one killed jessica', 'NULL', 'burmuda triangle', 'pokemon go', '', 0),
(244, 'Maulik', 'Ujval', 'maulik1792patel@gmail.com', 'mu', 8866252860, 'da', '12345678', 'Kailash Satyarthi', 'Tokyo(Japan)', 'Tim Cook', 'John Isner', 'M. Visvesvaraya', 'The Good, the Bad and the Ugly', '14th Fabruary', 'necessity is the mother of invention', 'June', 'trinitrotoluene(TNT band)', 'Thomas Edison', 'Usain bolt', 'Regression', '2011', 'NULL', 'ram teri ganga meli', 'NULL', 'NULL', 'pslv c-37 launcher', '', 0),
(250, 'anshu', 'bhargav', 'patelanshu860@gmail.com', 'abpj', 9913518175, 'DA', '123456', 'PM Narendra Modi Inaugurates Nobel Prize Exhibitio', 'olympic 2010 - canada', 'apple''s ceo tim cook fortune 500''s openly gay', 'NULL', 'APJ Abdul Kalam bharat ratna awarded', 'the good , the bad and the ugly', '14 feb', 'roti kapda makan', 'june', 'TNT', 'thomas edison', 'NULL', 'NULL', '2011', '', '', '', '', '', '', 0),
(251, 'mit', 'mitesh', '', 'gss', 9824641215, 'da', '1234567', 'Note Ban', 'NULL', 'Banned', 'Winner', 'Knight', 'Cowboy', 'Crush', 'Scholar', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', 1),
(252, 'Parth', 'Vaishvik', '', 'vp', 9724770670, 'da', '123456', 'Winston Churchill', 'Chichen Itza', 'Population', 'Kenilworth win', '2012 retirements', 'cowboys', 'Savages', 'inTELLIGENCE', 'June month', 'TNT explosive', 'Thomas Alva Edition', 'war', '', '', '', '', '', '', '', '', 0),
(260, 'kalpit', 'bhavik', 'kb', 'kb', 9925103799, 'DA', '123456789', 'Kailash Satyarthi', 'tokyo,japan', 'apple ceo tim cook', 'NULL', 'NULL', 'The Outlaw Josey Wales', '14th Feb', 'NULL', 'June', 'TNT band', '', '', '', '', '', '', '', '', '', '', 0);

-- --------------------------------------------------------

--
-- Table structure for table `quiz`
--

CREATE TABLE `quiz` (
  `id` int(11) NOT NULL,
  `question` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `quiz`
--

INSERT INTO `quiz` (`id`, `question`) VALUES
(1, 'http://14.139.122.117/grp/akash.jpg'),
(2, 'http://14.139.122.117/grp/biren.jpg'),
(3, 'http://14.139.122.117/grp/caught.jpg'),
(4, 'http://14.139.122.117/grp/dude.jpg'),
(5, 'http://14.139.122.117/grp/elephant.jpg'),
(6, 'http://14.139.122.117/grp/funk.jpg'),
(7, 'http://14.139.122.117/grp/gg.jpg'),
(8, 'http://14.139.122.117/grp/horney.jpg'),
(9, 'http://14.139.122.117/grp/intel.jpg'),
(10, 'http://14.139.122.117/grp/jaymil.jpg'),
(11, 'http://14.139.122.117/grp/kick.jpg'),
(12, 'http://14.139.122.117/grp/landload.jpg'),
(13, 'http://14.139.122.117/grp/mamu.jpg'),
(14, 'http://14.139.122.117/grp/Nano.jpg'),
(15, 'http://14.139.122.117/grp/os.jpg'),
(16, 'http://14.139.122.117/grp/parth.jpg'),
(17, 'http://14.139.122.117/grp/quote.jpg'),
(18, 'http://14.139.122.117/grp/roy.jpg'),
(19, 'http://14.139.122.117/grp/saurav.jpg'),
(20, 'http://14.139.122.117/grp/thanks.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `login`
--
ALTER TABLE `login`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `quiz`
--
ALTER TABLE `quiz`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `login`
--
ALTER TABLE `login`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=261;
--
-- AUTO_INCREMENT for table `quiz`
--
ALTER TABLE `quiz`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=21;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
